### ISSUE TITLE
Using target: "experimental-serverless-trace" config breaks the styles of the site

### ISSUE THREAD

**Issue by s-kris** [netlify/next-on-netlify#104]
I'm working with prisma for my site and ran into rhel binary issue. 
Fixed it as mentioned here: https://github.com/netlify/next-on-netlify/issues/55

The site's styles break with netlify deployment.
I tested the same codebase as a nodejs app deployment on my ec2 instance where the styles are rendered correctly.

**Comment by lindsaylevine** [comment]
@s-kris hey! would you mind opening a quick repo that reproduces this? would help a bunch!

**Comment by s-kris** [comment]
Sorry, I tied to recreate the bug with minimal chakra-ui repo, I'm not able to reproduce the bug.
I'll dig deeper in my main project later.

**Comment by s-kris** [comment]
I used next-on-netlify build plugin and redeployed the same code. The styles are working as expected now.
Closing the issue, thanks again! :)
