### ISSUE TITLE
Conflicting [slug] path and static page causing weird behavior in production

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/next-on-netlify#115]
**Describe the bug**
https://github.com/netlify/next-on-netlify/pull/75#issuecomment-743805067

This [live site reproduces the issue](https://fneinternacional.org/blog). If you click on a blog article and then click back, you should see that the blog page doesn't load, it hits the statically generated fallback page that just says Blog. Put another way, there's a page called blog on my wordpress CMS and next is statically generating that page and the explicitly created page title blog and they are colliding.

[Code is here](https://github.com/squamuglia/netlify-demo)

I don't wanna belabor this cuz I can always hack around the issue 😄  but it seems important that it happens on deploy but not local build.

---

@squamuglia thanks for sharing that additional info with me in your last comment!! i don't want to clutter the i18n PR with this and i'm not entirely sure it's an i18n issue (or even a NoN issue).

a few thoughts:
1. did this start happening only on the i18n branch? does it happen if you use NoN@2.6.3?
2. i'm not able to reproduce your issue. here's why - the repo you shared is definitely helpful, but because it's a fully-fledged app with API keys and what not, i'm not able to deploy it/run it/build it myself. i attempted to build and deploy an app of mine with /pages/static and /pages/[slug] where "static" is a path returned in getStaticPaths in /pages/[slug] with `fallback: true`. this wouldn't even let me complete the build so i'm not sure how you are. suggestions here are to open a much simpler repo that anyone can deploy that reproduces the issue.
3. i'm not sure a collision between these paths in your architecture is the responsibility of next-on-netlify or Next.js as a framework. have you tried using a catch-all (i.e. [...slug]) instead of just [slug]?

let me know!

**Comment by lindsaylevine** [comment]
@squamuglia can you address these thoughts described above (1-3)? otherwise we'll likely close this issue :)

**Comment by squamuglia** [comment]
I will update this report with more info soon and try those workarounds. However, I can confirm that the routes behave correctly when building without NoN on a node droplet.

**Comment by lindsaylevine** [comment]
ok let us know! the link in your original comment seems to be working as expected now (you may have introduced a workaround already?). again a minimal repo would be best - even if it's just the two pages that are conflicting. thanks!

**Comment by lindsaylevine** [comment]
@squamuglia hey checking in one last time before closing!
