### ISSUE TITLE
Redirecting from "getInitialProps" puts the response in html

### ISSUE THREAD

**Issue by JoviDeCroock** [netlify/next-on-netlify#116]
**Describe the bug**

When deploying an application on `netlify` with `next-on-netlify` which uses a page with `getInitialProps` that's used for redirecting, like the following:

```js
    res.writeHead(302, {
      Location: `en-us`,
    }).end();
```

It treats this as html, which means that we get to see a html-page which includes:

```json
{"isBase64Encoded":true,"multiValueHeaders":{"Location":["/en-us/"]},"statusCode":302}
```

rather than actually being redirected to the `pages/[locale]` handling this, this seems to work correctly when using `next dev`.

Error in netlify-logs:

```
ERROR	Unhandled error during request: Error: "Redirect.getInitialProps()" should resolve to an object. But found "undefined" instead.
    at loadGetInitialProps (/var/task/src/web/out_functions/next_index/nextJsPage.js:50131:11)
    at async Function.appGetInitialProps (/var/task/src/web/out_functions/next_index/nextJsPage.js:5470:21)
    at async Function.module.exports.cha2.App.getInitialProps (/var/task/src/web/out_functions/next_index/nextJsPage.js:35698:20)
    at async loadGetInitialProps (/var/task/src/web/out_functions/next_index/nextJsPage.js:50123:17)
    at async renderToHTML (/var/task/src/web/out_functions/next_index/nextJsPage.js:13361:1275)
    at async renderReqToHTML (/var/task/src/web/out_functions/next_index/nextJsPage.js:49246:22)
    at async Module.render (/var/task/src/web/out_functions/next_index/nextJsPage.js:49363:22)
```

Could this be because of the wrong `response-type` being detected?

EDIT: adding `return {}` to `getInitialProps` makes it work on netlify, trying to figure out why `props` being `undefined` is an issue on netlify but not on `next dev`.

I noticed this piece in the `NextPage.js` code

```
function isResSent(res) {
  return res.finished || res.headersSent;
}
```

When calling `res.end()` we should set `res.finished` to true, this is documented [here](https://nodejs.org/api/http.html#http_response_finished), we also got [`headersSent`](https://nodejs.org/api/http.html#http_response_headerssent) but don't know when to set this to true.

**To Reproduce**

Steps to reproduce:
1. Go to `/`
2. See html content being the JSON string

**Versions**
 - Next: 10.0.2
 - next-on-netlify: 2.6.3

**Comment by lindsaylevine** [comment]
hm if you're using Next 9.3 or greater (i see you're on Next 10) and [the docs](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) recommend using getServerSideProps or getStaticProps over getInitialProps in these later versions. 1. is this an issue using getServerSideProps instead? 2. what's your use case for getInitialProps over getServerSideProps?

**Comment by JoviDeCroock** [comment]
This issue seems general with both `getServerSideProps` and `getInitialProps`, the case for `getInitialProps` is a peculiar one.

In librarlies like `next-urql` a library called [react-ssr-prepass](https://github.com/FormidableLabs/react-ssr-prepass) is used, the same goes for `next-apollo` where it's called `getDataFromTree`. The `getInitialProps` method allows us to hook into our virtual dom-tree which allows for suspense-traversal. This means that we can use our `useQuery` hooks to fetch data rather than having to duplicate data-requirements in the `getServerSideProps` method.

**Comment by lindsaylevine** [comment]
gotcha ok makes sense, thanks for explaining that :) is this something you need hot-fixed out right now or can it wait til our next release?

**Comment by JoviDeCroock** [comment]
We have a temp-fix in place by returning the object for now so it can wait for the next release, thanks for following this up!

**Comment by lindsaylevine** [comment]
of course!! thanks for investigating and opening a PR, we super appreciate it!!
