### ISSUE TITLE
experimental-serverless-trace causes breaking build times and bundle sizes

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/next-on-netlify#120]
This is an issue to combine some of the miscellaneous, lingering issues in next-on-netlify that are all:

1. solved by changing target: serverless to target: experimental-serverless-trace
2. negatively impacted by the increased build times / bundle sizes

The related, miscellaneous issues:
[Preview mode broken in Next 10.0.2](https://github.com/netlify/next-on-netlify/issues/99)
[Functions fail when using Firebase Admin SDK](https://github.com/netlify/next-on-netlify/issues/68)
[Error enabling offline persistence with Firebase Web SDK and SSR](https://github.com/netlify/next-on-netlify/issues/66)

This also serves as a core issue/prerequisite before changing the default target we (a) recommend in the next-on-netlify docs (b) set in [@netlify/plugin-nextjs](https://github.com/netlify/netlify-plugin-nextjs).

[An amazing PR](https://github.com/netlify/zip-it-and-ship-it/pull/242) has been merged to `netlify/zip-it-and-ship-it` to help address this issue, thanks to the hard work of @erezrokah and @ehmicky ❤️ . This will be released in the new year!

**Comment by erezrokah** [comment]
FYI, the PR will be released to our build system in the new year as @lindsaylevine said, but it is available now in the CLI.
Running `netlify build` or `netlify deploy --build` will use the improved bundling logic when using `next-on-netlify`.

**Comment by erezrokah** [comment]
A quick update on this issue.
The fix has been released to our build system and we're seeing improvements on both bundle sizes and build times.
If anyone has a specific issue with functions bundle sizes/bundling time please open a new issue, possibly with a reproduction repo.
