### ISSUE TITLE
"blocking" on getStaticPaths' fallback throwing ambiguous error

### ISSUE THREAD

**Issue by TejasQ** [netlify/next-on-netlify#133]
**Describe the bug**
So my netlify site is `g2i-pace`, and it refuses to build if I want gSP to be blocking. 🤔  

![image](https://user-images.githubusercontent.com/9947422/103903803-a67b2100-50fc-11eb-9430-ae62bb315ae3.png)

**To Reproduce**
Steps to reproduce:
1. Create a basic page in a NextJS project with `fallback: "blocking"` in its exported `getStaticPaths` function
2. Build it on netlify with `next-on-netlify`
3. Cry

**Versions**
 - Next: `10.0.1`
 - next-on-netlify: `2.7.2`

**Comment by lindsaylevine** [comment]
hello hello @TejasQ ! thanks for opening and sorry about this :). lol @ step 3. i believe this is the same issue as https://github.com/netlify/next-on-netlify/issues/111 so i'll mark this as duplicate and close. please track it there! #111 is currently in our next 10 milestone https://github.com/netlify/next-on-netlify/milestone/1 so it's a priority!
