### ISSUE TITLE
Forward options params to "nextOnNetlify" function from node command-line args

### ISSUE THREAD

**Issue by jhesgodi** [netlify/next-on-netlify#165]
First of all, thanks for having a time to review.

**Is your feature request related to a problem? Please describe.**

I noticed **`nextOnNetlify`** function is invoked without any options param object at

[next-on-netlify.js#L15](https://github.com/netlify/next-on-netlify/blob/main/next-on-netlify.js#L15)
```javascript
...
const { logTitle } = require("./lib/helpers/logger");

nextOnNetlify();

logTitle("✅ Success! All done!");
...
```

But it already does accept passing down such object to set `functionsDir` and `publishDir`.

[index.js#L14-L21](https://github.com/netlify/next-on-netlify/blob/main/index.js#L14-L21)

```javascript
// https://github.com/netlify/next-on-netlify/blob/main/index.js

/** options param:
 * {
 *   functionsDir: string to path
 *   publishDir: string to path
 * }
 */

const nextOnNetlify = (options = {}) => {
    ...
```

This makes it impossible to use programatically from command line, like this:
```
next-on-netlify --publishDir=dist/.next --functionsDir=dist/.next/functions
```

Which is very handing when attempting to customly build a NextJS app locally, and then manually deploy using Netlify's CLI.

**Describe the solution you'd like**
Can these options params be forwarded down to the **`nextOnNetlify`** function, like this

```
next-on-netlify --publishDir=dist/.next --functionsDir=dist/.next/functions
```

by refactoring [next-on-netlify.js](https://github.com/netlify/next-on-netlify/blob/main/next-on-netlify.js) such params from command-line, like this?:

```
#!/usr/bin/env node
const { program } = require("commander");

program
  .option(
    "--max-log-lines [number]",
    "lines of build output to show for each section",
    50
  )
  .option(
    "--functionsDir [string]",
    "path to directory that contains the deploy-ready HTML files and assets generated by next the build.",
    undefined
  )
  .option(
    "--publishDir [string]",
    "path to directory with the serverless functions, including background functions.",
    undefined
  )
  .parse(process.argv);

const { functionsDir, publishDir } = program.opts();
const options = { functionsDir, publishDir }

const nextOnNetlify = require("./index");
const { logTitle } = require("./lib/helpers/logger");

nextOnNetlify(options);

logTitle("✅ Success! All done!");
```

**Describe alternatives you've considered**
One can always write its own node script mirroring the proposal above, but i'll consider that a workaround.
It will be ideal its base support from the package.

**Additional context**
I am particularly working with Nx plugin [@netlify-builder/deploy](https://github.com/ngx-builders/netlify-builder#readme).
My workflow looks like:

1. build next app into `dist/` directory. the next app is generated under `dist/.next` by NX, then
2. execute NoN targeting `dist/.next` to patch the files ready for Netlify by
  ```bash
       next-on-netlify --publishDir=dist/.next --functionsDir=dist/.next/functions
   ```
3. push `dist/.next` to Netlify using `@netlify-builder/deploy`

**Comment by lindsaylevine** [comment]
@jhesgodi hey! thanks so much for opening this issue :) this proposal is something we considered at the time that we introduced custom functionsDir and publishDir (_"already does accept passing down such object to set functionsDir and publishDir"_). it is a totally valid request and use case. here's why we opted not to support it:

per our [README](https://github.com/netlify/next-on-netlify#next-on-netlify-roadmap), the recommended path forward for building next projects on netlify is to use the official next.js plugin: https://github.com/netlify/netlify-plugin-nextjs. when using the plugin, you can specify your own functions and publish dirs in your netlify.toml (see plugin README for more details). we understand there are current NoN users who will continue to prefer the manual NoN setup; unfortunately, it's not in our scope to support both the [soon to be automated] plugin path and the manual NoN path. hope this makes sense!

sounds like you have a particular setup that would require some tweaking when you move to the plugin, but it should work all the same. happy to answer any questions and help you transition there!
