### ISSUE TITLE
Error decoding lambda response

### ISSUE THREAD

**Issue by wei** [netlify/next-on-netlify#17]
```
error decoding lambda response: error decoding lambda response: json: cannot unmarshal number into Go struct field APIGatewayProxyResponse.multiValueHeaders of type string
```
Related: https://community.netlify.com/t/error-decoding-lambda-response/16348

This issue started happening a couple days ago when netlify made an unannounced breaking change as seen in the ticket above.

The same repo I used in #9 is now broken without any changes.

Repo:
https://github.com/wei/next-on-netlify-demo-wei

Example:
https://relaxed-mirzakhani-568b34.netlify.app/api/debug/12345
https://relaxed-mirzakhani-568b34.netlify.app/api/debug/12345?testqs=1

I wonder if this is something that should be done in next-on-netlify library or on my side. Any help is appreciated! 🙇

**Comment by khawarjatoi** [comment]
There is no _next folder in any directory but I'm still getting same error when I try to deploy.

**Comment by adaam2** [comment]
@khawarjatoi I was on next v9, and upgrading to `10.0.4` fixed that issue for me :)

**Comment by khawarjatoi** [comment]
@adaam2 thanks man. I was also using v9.
