### ISSUE TITLE
Packaging Functions from out_functions directory never ends?

### ISSUE THREAD

**Issue by colinappnovation** [netlify/next-on-netlify#32]
"Packaging Functions from out_functions directory:" - seems to never end or take very long with Netlify cancelling build...

9:29:51 PM: Packaging Functions from out_functions directory:
9:29:51 PM:  - next_createlivefeedback/next_createlivefeedback.js
9:29:51 PM:  - next_feedbacksurvey_0introductionpage/next_feedbacksurvey_0introductionpage.js
9:29:51 PM:  - next_feedbacksurvey_11corevalues/next_feedbacksurvey_11corevalues.js
9:29:51 PM:  - next_feedbacksurvey_12corevalues/next_feedbacksurvey_12corevalues.js
9:29:51 PM:  - next_feedbacksurvey_13corevalues/next_feedbacksurvey_13corevalues.js
9:29:51 PM:  - next_feedbacksurvey_14corevalues/next_feedbacksurvey_14corevalues.js
9:29:51 PM:  - next_feedbacksurvey_2comment/next_feedbacksurvey_2comment.js
9:29:51 PM:  - next_feedbacksurvey_31skills/next_feedbacksurvey_31skills.js
9:29:51 PM:  - next_feedbacksurvey_32skills/next_feedbacksurvey_32skills.js
9:29:51 PM:  - next_feedbacksurvey_33skills/next_feedbacksurvey_33skills.js
9:29:51 PM:  - next_feedbacksurvey_34skills/next_feedbacksurvey_34skills.js
9:29:51 PM:  - next_feedbacksurvey_35skills/next_feedbacksurvey_35skills.js
9:29:51 PM:  - next_feedbacksurvey_36skills/next_feedbacksurvey_36skills.js
9:29:51 PM:  - next_feedbacksurvey_4comment/next_feedbacksurvey_4comment.js
9:29:51 PM:  - next_feedbacksurvey_completed/next_feedbacksurvey_completed.js
9:29:51 PM:  - next_index/next_index.js
9:29:51 PM:  - next_knowledgecenter_article/next_knowledgecenter_article.js
9:29:51 PM:  - next_knowledgecenter_search/next_knowledgecenter_search.js
9:29:51 PM:  - next_mylivefeedback/next_mylivefeedback.js
9:29:51 PM:  - next_mytasks/next_mytasks.js
9:29:51 PM:  - next_myteam/next_myteam.js
9:29:51 PM:  - next_mytools/next_mytools.js
9:29:51 PM:  - next_performance_editobjective/next_performance_editobjective.js
9:29:51 PM:  - next_performance_myobjectives/next_performance_myobjectives.js
9:29:51 PM:  - next_performance_myperformance/next_performance_myperformance.js
9:29:51 PM:  - next_performance_newobjective/next_performance_newobjective.js
9:29:51 PM:  - next_performance_submitreview/next_performance_submitreview.js
9:29:51 PM:  - next_performance_viewobjective/next_performance_viewobjective.js
9:29:51 PM:  - next_report_attachments/next_report_attachments.js
9:29:51 PM:  - next_report_corevalues/next_report_corevalues.js
9:29:51 PM:  - next_report_cover/next_report_cover.js
9:29:51 PM:  - next_report_info/next_report_info.js
9:29:51 PM:  - next_report_objectives/next_report_objectives.js
9:29:51 PM:  - next_report_openquestions/next_report_openquestions.js
9:29:51 PM:  - next_report_skills/next_report_skills.js
9:29:51 PM:  - next_report_writeup/next_report_writeup.js
9:29:51 PM:  - next_selfevaluation_0introductionpage/next_selfevaluation_0introductionpage.js
9:29:51 PM:  - next_selfevaluation_11corevalues/next_selfevaluation_11corevalues.js
9:29:51 PM:  - next_selfevaluation_12corevalues/next_selfevaluation_12corevalues.js
9:29:51 PM:  - next_selfevaluation_13corevalues/next_selfevaluation_13corevalues.js
9:29:51 PM:  - next_selfevaluation_14corevalues/next_selfevaluation_14corevalues.js
9:29:51 PM:  - next_selfevaluation_21myskills/next_selfevaluation_21myskills.js
9:29:51 PM:  - next_selfevaluation_22myskills/next_selfevaluation_22myskills.js
9:29:51 PM:  - next_selfevaluation_23myskills/next_selfevaluation_23myskills.js
9:29:51 PM:  - next_selfevaluation_24myskills/next_selfevaluation_24myskills.js
9:29:51 PM:  - next_selfevaluation_25myskills/next_selfevaluation_25myskills.js
9:29:51 PM:  - next_selfevaluation_26myskills/next_selfevaluation_26myskills.js
9:29:51 PM:  - next_selfevaluation_31yourobjectives/next_selfevaluation_31yourobjectives.js
9:29:51 PM:  - next_selfevaluation_32yourobjectives/next_selfevaluation_32yourobjectives.js
9:29:51 PM:  - next_selfevaluation_41performancereview/next_selfevaluation_41performancereview.js
9:29:51 PM:  - next_selfevaluation_42performancereview/next_selfevaluation_42performancereview.js
9:29:51 PM:  - next_selfevaluation_attachments/next_selfevaluation_attachments.js
9:29:51 PM:  - next_selfevaluation_completed/next_selfevaluation_completed.js
9:29:51 PM:  - next_skills_myskills/next_skills_myskills.js
....
9:42:31 PM: Canceling deploy
9:42:37 PM: Execution timed out after 17m7.720807482s
9:42:37 PM: Error running command: Command did not finish within the time limit
9:42:37 PM: Failing build: Failed to build site
9:43:07 PM: Failed to inform the API about a failed build, please retry the build or contact support
9:43:07 PM: Finished processing build request in 17m54.632197674s

**Comment by FinnWoelm** [comment]
Hi @colinappnovation,

That's definitely not how it should be! For those 13 minutes (from 9:29 to 9:42), is it packaging function after function or is it getting stuck somewhere for a long time?

I'm also surprised to see so many serverless functions. Generally, you can expect to see one serverless function per page — do you actually have this many different pages or do you just have a couple of pages that use dynamic/catch-all routing to render several routes?

Is your code available on GitHub for me to take a look at?

**Comment by colinappnovation** [comment]
Hi @FinnWoelm ,

Thank-you for your reply. I have not tried to debug as yet but have tried it locally through Netlify Build, and its 9 minutes with 12 cores and dedicated machine. So must be getting stuck or alike.

We do have that many pages ;) Unfortunately it is a client project, so cannot share code. Which I know is not very helpful.

**Comment by FinnWoelm** [comment]
Hi @colinappnovation,

Is this issue still relevant? Were you able to figure it out? I'm happy to help! :heart:

Otherwise, I'll close this issue for now (and we can reopen it if need be)

**Comment by FinnWoelm** [comment]
I'm closing this for now, but happy to reopen at any time!

**Comment by colinappnovation** [comment]
Hi @FinnWoelm,

Sorry for the late response on this. Putting 🔥 out on other things. Well things have been only resolved by 30 minute build window on Netlify. Things are now creeping up 23 minutes for a build. In comparison, ran the build and export on Vercel and was taking 3 minutes - though Vercel is built for Next so not really a comparison.

So issue is still apparent, just been alleviated by build timeout at present but looks like eventually in coming weeks will run out of build time, I would have thought.

With regards your initial questions about refactoring - the project is a dynamic HR system application, so there is very little static rendering, other than help pages etc. All other pages, are dynamic loading based on other consequential changes elsewhere in the system.

I am currently investing whether it is possible to allow access so can see raw material as it where to this problem.

**Comment by FinnWoelm** [comment]
Hey @colinappnovation, that sounds like a plan!

For context: Every single of your pages ends up becoming a separate serverless function that are anywhere from 1MB to 10MB (or more) in size, because all of the page's dependencies get bundled inline into the JS file. Each of those pages is then zipped and uploaded to Amazon AWS ("packaged"). And so with 100s or 1000s of pages, that will take a while. On Vercel, I think this process is faster because they don't zip and upload your functions.

If you can get permission, I'm happy to have a look and see if there is anything that can be done.
