### ISSUE TITLE
req.headers.host is undefined on netlify deployment

### ISSUE THREAD

**Issue by s-kris** [netlify/next-on-netlify#40]
I'm trying to read the host in getServerSideProps. It works in local environment with 
next dev (obviously) 
next build && netlify dev

However when deployed on netlify with this plugin, 
req.headers.host is undefined. Any info on this? Thank you.

**Comment by FinnWoelm** [comment]
Hi @s-kris, thanks for posting the issue!

Hmm, you are right. I just tested with a plain Netlify Function to see what information is available:

```js
exports.handler = function (event, context, callback) {
  callback(null, {
    statusCode: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
    },
    body: JSON.stringify({
      event,
      context,
    }),
  });
};
```

See results here: https://next-on-functions.netlify.app/.netlify/functions/print

Seems like host **is** available on `headers`, but **is not** available on `multiValueHeaders` (which is used by `next-on-netlify`). But we can manually add the host to the multiValueHeaders, that should be fine.

I'll let you know when it's done! :fire:

**Comment by s-kris** [comment]
Awesome, thank you @FinnWoelm

**Comment by leomeneguzzi** [comment]
Hi @FinnWoelm, do you have some update about it?

**Comment by leomeneguzzi** [comment]
Hi, I open a really simple PR that solves this issue. I need to do this to my project, just in case my PR be useful to you, I opened the PR. Case not, just close it.

**Comment by Yegair** [comment]
We are currently running into this issue and it prevents us from using next-on-netlify in production, do you have an ETA when this is going to be merged and released?

**Comment by abdelhamid-attaby** [comment]
@FinnWoelm can we solve this issue quickly? Our whole business depend on it :)

**Comment by FinnWoelm** [comment]
Hi all, sorry for the delay in getting this out the door! We were busy refactoring a lot of the codebase last week.

@lindsaylevine just merged the fix into `main`. The changes should be published to npm within the next 24 hours. If you prefer not to wait, you can already use the latest changes by running npm install netlify/next-on-netlify#main --save. This will give you the cutting-edge version of `next-on-netlify` right away.

PS: We are **super** excited that @lindsaylevine has joined Netlify and the `next-on-netlify` team! :raised_hands:  @lindsaylevine has a ton of experience and will help push `next-on-netlify` to the next level. You will be seeing a lot of @lindsaylevine going forward :grin: :clap:

**Comment by s-kris** [comment]
@FinnWoelm @lindsaylevine That's great to hear. Looking forward to new major features. (hint: pure next-inc-ssg support) 
Thanks for your awesome work!

**Comment by depadiernos** [comment]
Just wanted to add here that I added the 'host' header to the multiValueHeaders object for functions on the netlify-side of things. It's currently being deployed but should be live on our regular CDN and will be live on our Enterprise CDN soon.
