### ISSUE TITLE
Broken redirects with optional catch-all route at top-level in pages/

### ISSUE THREAD

**Issue by amuttsch** [netlify/next-on-netlify#45]
### What's wrong

With version `2.4.0` `yarn run build` produces the following (correct) `out_publish/_redirects` file:

```
# Next-on-Netlify Redirects
/api  /.netlify/functions/next_api  200
*  /.netlify/functions/next_any  200
```

Using `2.5.0` the sorting has changed, and the catch all rules are before the specific ones:

```
# Next-on-Netlify Redirects
/*  /.netlify/functions/next_any  200
  /.netlify/functions/next_any  200
/api  /.netlify/functions/next_api  200
```

We can see the `/*` catch route is before the `/api` route. Additionally, there is a new (and possible invalid) redirect.

Now the requests to `/api` are routed to `/` and the specific handler is not called.

### How to reproduce

I created a minimal example repo here: https://github.com/amuttsch/next-on-netlify-minimal

To reproduce just change the version of `next-on-netlify` in the `package.json` to `2.4.0` or `2.5.0` and run `yarn install && yarn run build`.

Thanks for your work on this package!

**Comment by FinnWoelm** [comment]
Hey @amuttsch, thanks for filing this issue and for your detailed report!

This one is totally my bad! :grimacing: :see_no_evil:  Looks like I missed this scenario when we did a major refactor last week. You have an optional catch-all route at project root, is that right? @lindsaylevine and I will fix this tonight and make sure to add a test, so it doesn't happen again in the future!

We'll keep you posted!

**Comment by amuttsch** [comment]
Hi Finn,

yes I do have a root level catch all route, it also happens if I have a separate `index.jsx` and a `[any.jsx]` file.

Thanks for your quick reply, I'm looking forward for the fix :-)

**Comment by FinnWoelm** [comment]
Turns out that I actually introduced not just one, but two bugs during the refactoring! :grimacing: But I think we got it figured out and #47 will fix that :raised_hands: :raised_hands: 

If you're in a hurry, you can already try out the new code by running `npm install netlify/next-on-netlify#fix-broken-redirects`. Otherwise, I think we'll get this reviewed, merged, and deployed shortly :slightly_smiling_face:

**Comment by FinnWoelm** [comment]
Hi @amuttsch, this issue should be resolved now :blush: :fire: Let us know if you have any more trouble and thanks again for reporting!

**Comment by amuttsch** [comment]
The fix looks good, thanks for the quick response! :-)
