### ISSUE TITLE
Error during build step `index.html already exists`

### ISSUE THREAD

**Issue by miamollie** [netlify/next-on-netlify#48]
Hi there,

Thanks for the great project! 

I've encountered this error while building a prod version of my nextJS app (dev version is fine):

`Error: 'out_publish/index.html' already exists`

I first saw this in the netlify CI, but was able to reproduce locally too. I have already followed the instructions [here](https://github.com/netlify/next-on-netlify#preview-locally). 

You can see my repo [here](https://github.com/miamollie/plantnow), it's a pretty basic setup and definitely doesn't have a spare `index.js` in the pages directory messing with things :)

Based on the build output, it looks like it is picking up two `index.html` files to copy

![image](https://user-images.githubusercontent.com/8226903/95004241-66eff500-0634-11eb-9d83-c99ac0719b31.png)

But I don't see that in the `.next` output myself:

![image](https://user-images.githubusercontent.com/8226903/95004258-9999ed80-0634-11eb-980c-bd66b7d35b41.png)

Deps:

```
"next-on-netlify": "^2.4.0",
"next": "latest", // evaluated to 9.4.4
```

Thanks again for your great work, let me know if I can provide any more details to help debug this issue.

**Comment by pedrobullo** [comment]
Downgrade to v2.4.0, should fix for now. :(

**Comment by FinnWoelm** [comment]
Hey @pedrobullo,

Thank you for the kind words! And sorry about the issue :scream: 

There are some differences between v9.4 and v9.5 of `next`, that affect the serverless page generation. At the moment, `next-on-netlify` is focused on providing support for the latest version of NextJS. Do you mind upgrading to v9.5.3? I have already created a PR for you: https://github.com/miamollie/plantnow/pull/5

Does that work for you? :blush:

PS: This issue does raise a topic that will be important going forward: Improving our documentation of which versions are supported and/or adding support for previous versions of NextJS. We want to focus on first adding missing features to `next-on-netlify`, but we'll keep this issue on our mind!

**Comment by miamollie** [comment]
Hi @FinnWoelm  @pedrobullo ,

Thanks for looking into this for me and for the upgrade fix. That did the trick! 

I might not be able to contribute a fix for the issue, but I'd certainly be happy to help with documentation if you need more hands. Might I suggest for now including the supported version as part of your caveats?
