### ISSUE TITLE
Error: Cannot find module 'next-aws-lambda' when using yarn 2 

### ISSUE THREAD

**Issue by rizkyramadhan** [netlify/next-on-netlify#56]
"Cannot find module 'next-aws-lambda'\n" +
    'Require stack:\n' +
    '- C:\\Users\\Riz\\Desktop\\basey2\\out_functions\\next_api_hello\\next_api_hello.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\lambda-local\\build\\lambdalocal.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\src\\utils\\serve-functions.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\src\\commands\\dev\\index.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\@oclif\\config\\lib\\plugin.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\@oclif\\config\\lib\\config.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\@oclif\\config\\lib\\index.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\@oclif\\command\\lib\\command.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\node_modules\\@oclif\\command\\lib\\index.js\n' +
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\src\\index.js\n' +     
    '- C:\\Users\\Riz\\scoop\\persist\\nvm\\nodejs\\v14.10.1\\node_modules\\netlify-cli\\bin\\run',

**Comment by lindsaylevine** [comment]
hey @rizkyramadhan, thanks for filing this! what command(s) are you running that lead you to seeing this local error?

**Comment by rizkyramadhan** [comment]
netlify dev, 

or just push to the repo and let netlify CD deploy my app

**Comment by rizkyramadhan** [comment]
FYI, I'm on windows 10. But I think netlify environment is in linux., and this happens on both env.

**Comment by lindsaylevine** [comment]
hmm ok. not sure what's going on without really seeing the context. are you able to create a repo that reproduces this issue?

**Comment by lindsaylevine** [comment]
hey rizky! following up here since this has been open for a little while :) any update? otherwise, we'll close this issue due to inactivity.

**Comment by rizkyramadhan** [comment]
Sorry, closed this for now, I decided to host on my on server without `serverless` function
