### ISSUE TITLE
Set custom function route for Netlify identity hooks

### ISSUE THREAD

**Issue by BrandonKlotz** [netlify/next-on-netlify#57]
Hi, I was wondering if there is a way to set functions as custom routes that will be picked up by Netlify's identity hooks.

The function that is produced in `next-on-netlify`:
![Screen Shot 2020-10-15 at 5 14 34 PM](https://user-images.githubusercontent.com/19940878/96188744-3ef27280-0f0d-11eb-8d5f-6b9d5f4eb24d.png)
- This is a Next.js app deployed with Next on Netlify (https://github.com/BrandonKlotz/netlify-identity-hooks)

What I _think_ Netlify Identity will trigger when someone signs up:
![Screen Shot 2020-10-15 at 5 14 50 PM](https://user-images.githubusercontent.com/19940878/96188814-60535e80-0f0d-11eb-9270-5184b94aa0ea.png)
- This is deployed using Eleventy.js with a functions folder (https://github.com/stripe-samples/netlify-stripe-subscriptions)

Looking at the docs:
https://docs.netlify.com/functions/functions-and-identity/#trigger-serverless-functions-on-identity-events

I looked at the issue related to (https://github.com/netlify/next-on-netlify#custom-netlify-functions) but don't know that it is the same need here.

This is a weird question/issue I don't know if it is a feature request or a misunderstanding of how these two things interact. Happy to make this an example and add to docs when I better understand what's going on 😂

**Comment by lindsaylevine** [comment]
hey! thanks for opening this :). glad you found the custom netlify functions caveat/related issue. it's high on my list of priorities to support and will be included in the next major release. a _potential_ workaround if you really needed it would be to build with the CLI, copy your custom function into out_functions and then deploy that.

1. `netlify deploy --build`
2. copy identity-signup.js into out_functions
3. `netlify deploy --prod`

**Comment by BrandonKlotz** [comment]
@lindsaylevine so I was trying to follow the steps you have to deploy from the CLI but also new to using Netlify CLI, so a lot of today I learned's but wasn't able to copy over the identity-signup into `out_functions` (I tried also taking this folder out of my `.gitignore`.

Thinking about this as a feature, it would be kind of interesting not change the file names in the same way we change api routes. I am imagining a [list of all the function names that trigger by events](https://docs.netlify.com/functions/trigger-on-events/#available-triggers) and then in `lib/helpers/setupNetlifyFunctionForPage.js` when we find a file that has one of these functions `['deploy-building', 'deploy-locked', 'identity-signup']` we just copy that over to the specified functions folder _likely_ `out_functions`

I am trying to test this out locally and will post an update if I make any progress 😄

**Comment by BrandonKlotz** [comment]
Made a work in progress/draft pull to work on this idea https://github.com/netlify/next-on-netlify/pull/60

**Comment by BrandonKlotz** [comment]
The good news, I think it is closer to working! 🎉 

<img width="403" alt="Screen Shot 2020-10-16 at 9 44 21 PM" src="https://user-images.githubusercontent.com/19940878/96325779-d54f9280-0ff8-11eb-90e7-f6dadb09fe33.png">

The other good news, I am about to learn how to write a working Netlify function 🤣

**Comment by BrandonKlotz** [comment]
So I found out why I was running into some weirdness. 

Steps to fixing:
1. Found similar [issue here](https://github.com/vercel/next.js/issues/9643)
2. `yarn add micro@canary`
3. Chose canary `9.3.5-canary.3`
4. Commit and push those changes
5. Then build and deploy from Netlify CLI so I can use the local version of `next-on-netlify`

After signing up, the trigger event function properly ran! 

<img width="1238" alt="Screen Shot 2020-10-17 at 9 03 18 AM" src="https://user-images.githubusercontent.com/19940878/96337889-45d9cc00-1058-11eb-8b9c-235d6f1e2940.png">

**Comment by lindsaylevine** [comment]
hey @BrandonKlotz! thanks so much for working on this :). i'm going to be super distracted this week likely with other priorities but will try to check in on your progress/PR.

**Comment by BrandonKlotz** [comment]
Sweet! As I understood better what I needed, #60 is a quick out-of-the-box way to support the Netlify Event Trigger Functions for those using `next-on-netlify`. 

The feature people have requested of custom function routes likely could also achieve the needs I have here, I could see that being the solution that eclipses this feature proposal. I had a lot of fun learning about this package through trying to make it support Trigger Functions.

Also was thinking another good issue I could probably add is write unit tests for the `helpers/` folder. Think it would be a good way for me to contribute and learn more about each helper.

**Comment by lindsaylevine** [comment]
@BrandonKlotz sorry been swamped. i think you're right @ custom functions, which is Coming Soon TM. i'm glad you had fun working with next-on-netlify and trigger functions!!! :) we'd be lucky to have you contribute tests or contribute in general to the project!
