### ISSUE TITLE
Can't deploy nextjs on netlify throw new Error(`'${dest}' already exists`) at /opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62

### ISSUE THREAD

**Issue by antonygunawan94** [netlify/next-on-netlify#79]
Hello,
I have followed the instructions in readme.md but got this error

`11:18:41 AM: /opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62
11:18:41 AM:     throw new Error(`'${dest}' already exists`)
11:18:41 AM:     ^
11:18:41 AM: Error: 'out_functions/next_glossarium_slug/next_glossarium_slug.js' already exists
11:18:41 AM:     at mayCopyFile (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
11:18:41 AM:     at onFile (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
11:18:41 AM:     at getStats (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
11:18:41 AM:     at startCopy (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
11:18:41 AM:     at handleFilterAndCopy (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
11:18:41 AM:     at copySync (/opt/build/repo/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
11:18:41 AM:     at setupNetlifyFunctionForPage (/opt/build/repo/node_modules/next-on-netlify/lib/helpers/setupNetlifyFunctionForPage.js:21:3)
11:18:41 AM:     at /opt/build/repo/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:21:5
11:18:41 AM:     at Array.forEach (<anonymous>)
11:18:41 AM:     at setup (/opt/build/repo/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:17:9)
11:18:41 AM: npm ERR! code ELIFECYCLE
11:18:41 AM: npm ERR! errno 1
11:18:41 AM: npm ERR! glowlab@0.1.0 postbuild: `next-on-netlify`
11:18:41 AM: npm ERR! Exit status 1
11:18:41 AM: npm ERR!
11:18:41 AM: npm ERR! Failed at the glowlab@0.1.0 postbuild script.
11:18:41 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:18:41 AM: npm ERR! A complete log of this run can be found in:
11:18:41 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-14T04_18_41_667Z-debug.log`

anyone having the same problem?

**Comment by cassidoo** [comment]
Hey! Do you have a repo or anything we can look at to debug a little further?

**Comment by antonygunawan94** [comment]
yes but it is private, I'll invite you to the repo

**Comment by antonygunawan94** [comment]
I think the cause of this is the fallback param in getStaticPaths because when I switched to getServerSideProps in works just fine

**Comment by lindsaylevine** [comment]
@antonygunawan94 can you add me as well?

**Comment by antonygunawan94** [comment]
hello, 
I think I will close this issue because I've already found the solution by switching to server side rendering
thank you so much to netlify team for the quick responses

**Comment by lindsaylevine** [comment]
ok let us know if you change your mind. your source code and more context would help us potentially diagnose this for other next-on-netlify users :). our best!

**Comment by ehmicky** [comment]
It looks like this error [is happening pretty frequently](https://app.bugsnag.com/netlify/netlify-build/errors/5fc6eda143d1b30017cae1c0) in production.

[Example build](https://app.netlify.com/sites/kultaapp/deploys/5ff72e4e4449ef00077fcc3b)

```
4:54:34 PM: ────────────────────────────────────────────────────────────────
4:54:34 PM:   3. onBuild command from @netlify/plugin-nextjs                
4:54:34 PM: ────────────────────────────────────────────────────────────────
4:54:34 PM: ​
4:54:34 PM: ** Running Next on Netlify package **
4:54:34 PM: 🚀 Next on Netlify 🚀
4:54:34 PM: 🌍️ Copying public/ folder to /opt/build/repo
4:54:34 PM: 💼 Copying static NextJS assets to /opt/build/repo
4:54:34 PM: 💫 Setting up API endpoints as Netlify Functions in netlify-automatic-functions
4:54:34 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in netlify-automatic-functions
4:54:34 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in netlify-automatic-functions
4:54:34 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo
4:54:34 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in netlify-automatic-functions
4:54:34 PM: ​
4:54:34 PM: ────────────────────────────────────────────────────────────────
4:54:34 PM:   Plugin "@netlify/plugin-nextjs" internal error                
4:54:34 PM: ────────────────────────────────────────────────────────────────
4:54:34 PM: ​
4:54:34 PM:   Error message
4:54:34 PM:   Error: 'netlify-automatic-functions/next_category/next_category.js' already exists
4:54:34 PM: ​
4:54:34 PM:   Plugin details
4:54:34 PM:   Package:        @netlify/plugin-nextjs
4:54:34 PM:   Version:        1.0.5
4:54:34 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
4:54:34 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
4:54:34 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
4:54:34 PM: ​
4:54:34 PM:   Error location
4:54:34 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
4:54:34 PM:       at mayCopyFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
4:54:34 PM:       at onFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
4:54:34 PM:       at getStats (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
4:54:34 PM:       at startCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
4:54:35 PM:       at handleFilterAndCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
4:54:35 PM:       at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
4:54:35 PM:       at setupNetlifyFunctionForPage (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/helpers/setupNetlifyFunctionForPage.js:21:3)
4:54:35 PM:       at /opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:20:5
4:54:35 PM:       at Array.forEach (<anonymous>)
4:54:35 PM:       at setup (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/pages/getStaticPropsWithFallback/setup.js:16:9)
```

The line failing is:

https://github.com/netlify/next-on-netlify/blob/ae79eb03feb2c9f86ae4823d3bb1f1c070883281/lib/helpers/setupNetlifyFunctionForPage.js#L21

Specifically, `errorOnExit` is `true`, but the file being copied seems to already exist in the destination directory.

This also happens for this line, for the same reason:

https://github.com/netlify/next-on-netlify/blob/ae79eb03feb2c9f86ae4823d3bb1f1c070883281/lib/helpers/setupStaticFileForPage.js#L15

[Example build](https://app.netlify.com/sites/ecstatic-hodgkin-d4a2b3/deploys/5feaa90f464cdc0008e22bae)

```
4:57:44 AM: ────────────────────────────────────────────────────────────────
4:57:44 AM:   3. onBuild command from @netlify/plugin-nextjs                
4:57:44 AM: ────────────────────────────────────────────────────────────────
4:57:44 AM: ​
4:57:44 AM: ** Running Next on Netlify package **
4:57:44 AM: 🚀 Next on Netlify 🚀
4:57:44 AM:    Functions directory:  netlify-automatic-functions
4:57:44 AM:    Publish directory:  /opt/build/repo
4:57:44 AM:    Make sure these are set in your netlify.toml file.
4:57:44 AM: 🌍️ Copying public/ folder to /opt/build/repo
4:57:44 AM: 💼 Copying static NextJS assets to /opt/build/repo
4:57:44 AM: 💫 Setting up API endpoints as Netlify Functions in netlify-automatic-functions
4:57:44 AM: 💫 Setting up pages with getInitialProps as Netlify Functions in netlify-automatic-functions
4:57:44 AM: 💫 Setting up pages with getServerSideProps as Netlify Functions in netlify-automatic-functions
4:57:44 AM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo
4:57:44 AM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in netlify-automatic-functions
4:57:44 AM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in netlify-automatic-functions
4:57:44 AM: 🔥 Copying pre-rendered pages without props to /opt/build/repo
4:57:44 AM: ​
4:57:44 AM: ────────────────────────────────────────────────────────────────
4:57:44 AM:   Plugin "@netlify/plugin-nextjs" internal error                
4:57:44 AM: ────────────────────────────────────────────────────────────────
4:57:44 AM: ​
4:57:44 AM:   Error message
4:57:44 AM:   Error: '/opt/build/repo/index.html' already exists
4:57:44 AM: ​
4:57:44 AM:   Plugin details
4:57:44 AM:   Package:        @netlify/plugin-nextjs
4:57:44 AM:   Version:        1.0.3
4:57:44 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
4:57:44 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
4:57:44 AM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
4:57:44 AM: ​
4:57:44 AM:   Error location
4:57:44 AM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
4:57:44 AM:       at mayCopyFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
4:57:44 AM:       at onFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
4:57:44 AM:       at getStats (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
4:57:44 AM:       at startCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
4:57:44 AM:       at handleFilterAndCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
4:57:44 AM:       at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
4:57:44 AM:       at setupStaticFileForPage (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/helpers/setupStaticFileForPage.js:15:3)
4:57:44 AM:       at /opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/pages/withoutProps/setup.js:19:5
4:57:44 AM:       at Array.forEach (<anonymous>)
4:57:44 AM:       at setup (/opt/build/repo/.netlify/plugins/node_modules/next-on-netlify/lib/pages/withoutProps/setup.js:14:9)
```

**Comment by FinnWoelm** [comment]
`errorOnExist: true` exists as a safety precaution to make sure that we a) never accidentally overwrite the user's files or functions and b) catch bugs where NoN writes two files to the same name.

The latter can happen for our Netlify Functions, because when we convert the page's file name to Netlify Function name, we strip all non-alphanumeric characters (except underscore). So page `my-[page].js` and `my-page.js` will try to write the same function name. See [`getNetlifyFunctionName.js`](https://github.com/netlify/next-on-netlify/blob/main/lib/helpers/getNetlifyFunctionName.js). This needs to be addressed at some point, but perhaps in a separate issue.

Just adding my two cents that we should identify why NoN is writing two files to the same destination and fix that issue rather than just setting `errorOnExists: false` 😊

**Comment by ehmicky** [comment]
Thanks for the additional context @FinnWoelm!
Please let me know if I should re-close this issue.
