### ISSUE TITLE
getServerSideProps fails for certain values, probably related to URL encoding or slashes

### ISSUE THREAD

**Issue by phbernard** [netlify/next-on-netlify#98]
In `getServerSideProps`, some values accessible via `context.params` are sometimes wrong.

In particular, **the behavior of next-on-netlify differs from local and Vercel**.

# To reproduce the issue in a few seconds, on Netlify and Vercel

The [demo app](https://github.com/phbernard/next-on-netlify-demo-app) is deployed. You can play with various values to check the outcome.

* Vercel :
    * https://next-on-netlify-demo-app.vercel.app/somedir/somestuff : Prints `Variable: somestuff`, as expected
    * https://next-on-netlify-demo-app.vercel.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable: http://example.com/`, as expected
* Netlify with next-on-netlify:
    * https://clever-poincare-8cd163.netlify.app/somedir/somestuff : Prints `Variable: somestuff`, as expected
    * https://clever-poincare-8cd163.netlify.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable:`, there is no value, which is **not** expected

# To reproduce the issue from scratch, on all environments

- Create a NextJS app:

`npx create-next-app`

- Create `pages/somedir/[someVar].jsx` and populate it with:

```
export default function SomeVar({ someVar })  {
  return (
    <html>
      <body>
        Variable: {someVar}
      </body>
    </html>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      someVar: context.params.someVar
    }
  }
}
```
This page simply prints the value of the variable `someVar`.

* Run the app locally:

`npm run dev`

* Test the page with a regular value and URL-like value:

    * http://localhost:3000/somedir/somestuff : Prints `Variable: somestuff`, as expected
    * http://localhost:3000/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable: http://example.com/`, as expected

* Deploy the app to Vercel.

* Test the page with a regular value and URL-like value:

    * https://THE_APP.vercel.app/somedir/somestuff : Prints `Variable: somestuff`, as expected
    * https://THE_APP.vercel.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable: http://example.com/`, as expected

* Configure the app with next-on-netlify as described in the README of the project (install next-on-netlify, create `next.config.js` and `netlify.toml`).

* Deploy the app to Netlify.

* Test the page with a regular value and URL-like value:

    * https://THE_APP.netlify.app/somedir/somestuff : Prints `Variable: somestuff`, as expected
    * https://THE_APP.netlify.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable:`, there is no value, which is **not** expected

What makes the process fails is not clear:

* https://THE_APP.netlify.app/somedir/http%3A : Prints `Variable: http:`, as expected
* https://THE_APP.netlify.app/somedir/http%3A%2F : Prints `Variable: http:`, the final slash is missing
* https://THE_APP.netlify.app/somedir/http%3A%2F%2F : Prints `Variable:`, now the value is empty

**Comment by lindsaylevine** [comment]
hey @phbernard thanks so much for opening such a detailed issue! we _super_ appreciate it, and it's made it much easier to start diagnosing. unfortunately it isn't immediately clear to us, even with the perfect reproduction, why this is happening so we'll keep you updated <3.

**Comment by lindsaylevine** [comment]
@phbernard update!! we identified the issue internally. a PR is open but unfortunately it's considered "low risk" week here due to the holiday so it wont be rolled out until next thursday. i'll let you know!!

**Comment by mraerino** [comment]
this is a detailed update on the bugfix: https://community.netlify.com/t/bug-fix-url-encoding-preserved-in-function-event-not-released/27080
you will hear about the rollout there first, but i will also update here.

**Comment by phbernard** [comment]
Not sure this is the place to post this, but I think `getServerSideProps` might be currently broken in NetxtJS projects hosted on Netlify.

The recent update of next-on-netlify, probably peering with the new [Next.js build plugin](https://www.netlify.com/blog/2020/12/07/announcing-one-click-install-next.js-build-plugin-on-netlify/), might break the regular `getServerSideProps` behavior.

This is the new behavior of the demo project, already used in the first issue description above (they were not updated or re-deployed since then):

- Vercel :

    - https://next-on-netlify-demo-app.vercel.app/somedir/somestuff : Prints `Variable: somestuff`, as expected
    - https://next-on-netlify-demo-app.vercel.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable: http://example.com/`, as expected

- Netlify with next-on-netlify:

    - https://clever-poincare-8cd163.netlify.app/somedir/somestuff : Prints `Variable:`, there is no value. **This is a new behavior and definitely not as expected.**
    - https://clever-poincare-8cd163.netlify.app/somedir/http%3A%2F%2Fexample.com%2F : Prints `Variable: http://example.com/`, which is a new behavior. As far as I understand, this is not what is described in https://community.netlify.com/t/bug-fix-url-encoding-preserved-in-function-event-not-released/27080.

**Comment by phbernard** [comment]
For the record, the change I described 2 hours ago was rolled back (https://community.netlify.com/t/bug-fix-url-encoding-preserved-in-function-event/27080/4)

**Comment by jlengstorf** [comment]
here's a reproduction from @JoviDeCroock showing what appears to be URL-encoding issues. these issues _are not_ present in local development with Netlify Dev, if that helps with debugging

* https://stupefied-ritchie-9883b6.netlify.app/
* https://github.com/JoviDeCroock/netlify-next-issue

**Comment by emilyzhang** [comment]
Just a heads up: the fix for this issue (netlify/proxy#430) has been rolled out to all production nodes!

**Comment by JoviDeCroock** [comment]
Awesome, thank you for the update @emilyzhang

**Comment by lindsaylevine** [comment]
thank you @emilyzhang !!!!!!! @phbernard can you confirm your original issue is resolved? :) 🙏

**Comment by phbernard** [comment]
It's resolved! 🎉

Now https://clever-poincare-8cd163.netlify.app/somedir/http%3A%2F%2Fexample.com%2F prints `Variable: http://example.com/`, like Vercel.

Thank you! 🙏
